server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring # queue
      dead-letter:
        producer: dl.producer.aula-spring
